### ISSUE TITLE
rankings

### ISSUE THREAD

**Issue by getkirill** [GuglioIsStupid/Rit#12]
SS, S, A, or whatever
i need letters to know how awful my galaxy collapse gameplay was
also endscreen that shows that maybe?

**Comment by GuglioIsStupid** [comment]
yeah i've been thinking of adding an endscreen and saving highscores and what-not, just trying to fix some bugs first before i add some more that i'll have deal w/ later lol

**Comment by getkirill** [comment]
probably fixed in 27c827..78bf31
