### ISSUE TITLE
somehow when you fail blue zenith mint's hard it duplicates itself

### ISSUE THREAD

**Issue by getkirill** [GuglioIsStupid/Rit#6]
needs more observation
![image](https://user-images.githubusercontent.com/26975352/216085125-27b3473c-deb4-458e-b1b9-54341c4e3f90.png)

**Comment by GuglioIsStupid** [comment]
weird, is it specifically that chart? (I'd assume it would happen with others and i may know why)

**Comment by getkirill** [comment]
failing galaxy collapse doesn't trigger that

**Comment by GuglioIsStupid** [comment]
weird, can you send that chart on discord?

**Comment by getkirill** [comment]
whoops not all but zenith

**Comment by GuglioIsStupid** [comment]
i think i fixed it, i had all the charts load into the game every time song select state is entered, it doesn't clear the list before hand so im guessing it just re adds it

**Comment by getkirill** [comment]
ye looks fixed
